import React from 'react';
import { motion } from 'framer-motion';
import { Terminal, Copy, Check, ArrowLeft, AlertCircle } from 'lucide-react';
import { Link } from 'react-router-dom';

const CodeBlock: React.FC<{ code: string; lang?: string }> = ({ code, lang = 'javascript' }) => {
  const [copied, setCopied] = React.useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="relative border-2 border-black dark:border-white bg-black text-white p-6 my-6 shadow-brutal-sm font-mono text-sm overflow-x-auto">
      <div className="absolute top-0 right-0 p-2">
        <button 
          onClick={handleCopy}
          className="flex items-center gap-1 text-xs uppercase font-bold text-gray-400 hover:text-brand-teal transition-colors"
        >
          {copied ? <Check size={14} /> : <Copy size={14} />}
          {copied ? 'Copied' : 'Copy'}
        </button>
      </div>
      <pre><code>{code}</code></pre>
    </div>
  );
};

export const TechArticle1: React.FC = () => {
  return (
    <div className="min-h-screen bg-white dark:bg-black text-black dark:text-white font-sans">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-20">
        
        {/* Breadcrumb */}
        <Link to="/tech" className="inline-flex items-center gap-2 font-mono text-sm font-bold uppercase mb-8 hover:text-brand-teal">
          <ArrowLeft size={16} /> Back to Tech Hub
        </Link>

        {/* Header */}
        <div className="border-b-4 border-black dark:border-white pb-8 mb-12">
          <div className="inline-block px-2 py-1 bg-brand-teal text-white border border-black dark:border-white font-mono text-xs font-bold uppercase mb-4">
            Beginner Tutorial
          </div>
          <h1 className="text-4xl md:text-6xl font-black uppercase leading-none mb-6">
            Your First Script: <br/><span className="text-brand-amber">"Hello, Legal World"</span>
          </h1>
          <p className="font-mono text-lg text-gray-600 dark:text-gray-400">
            Stop being afraid of the code editor. In 10 minutes, you'll write a script that creates a Google Doc automatically. No installation required.
          </p>
        </div>

        {/* Content */}
        <article className="prose prose-lg dark:prose-invert max-w-none font-mono">
          
          <div className="bg-brand-gray dark:bg-zinc-900 border-2 border-black dark:border-white p-6 mb-12 shadow-brutal-sm">
            <h3 className="font-bold uppercase text-lg mb-2 flex items-center gap-2">
              <Terminal size={20} /> Prerequisites
            </h3>
            <ul className="list-disc pl-4 space-y-1 text-sm">
              <li>A Google Account (Gmail)</li>
              <li>A web browser (Chrome recommended)</li>
              <li>Zero coding knowledge</li>
            </ul>
          </div>

          <h2 className="text-2xl font-black uppercase mb-4">Step 1: Open the Editor</h2>
          <p className="mb-4">
            Lawyers pay thousands for document automation software. We're going to use a tool you already have for free: <strong>Google Apps Script</strong>.
          </p>
          <ol className="list-decimal pl-6 space-y-2 mb-8">
            <li>Go to <a href="https://script.google.com" target="_blank" className="underline decoration-2 underline-offset-2 hover:text-brand-teal">script.google.com</a>.</li>
            <li>Click the big button that says <strong>"New Project"</strong>.</li>
            <li>You are now looking at a code editor. Don't panic.</li>
          </ol>

          <h2 className="text-2xl font-black uppercase mb-4">Step 2: Write Your First Function</h2>
          <p className="mb-4">
            Delete any code you see in the editor (usually <code>function myFunction() &#123;...&#125;</code>) and paste this in its place.
          </p>
          <p className="mb-4">
            This script tells Google Drive to create a new Google Doc named "Hello Legal World".
          </p>

          <CodeBlock code={`function createMyFirstDoc() {
  // 1. Define the name of the document
  var docName = "Hello Legal World - Generated by Script";
  
  // 2. Ask the DocumentApp service to create it
  var doc = DocumentApp.create(docName);
  
  // 3. Get the 'body' of the document so we can write in it
  var body = doc.getBody();
  
  // 4. Append a paragraph of text
  body.appendParagraph("This document was created by code, not by hand.");
  body.appendParagraph("Welcome to legal automation.");
  
  // 5. Log the URL so we can find it
  Logger.log("Success! Created document at: " + doc.getUrl());
}`} />

          <h2 className="text-2xl font-black uppercase mb-4">Step 3: Run It</h2>
          <ol className="list-decimal pl-6 space-y-2 mb-8">
            <li>Click the <strong>Save</strong> icon (floppy disk) or press <code>Ctrl + S</code>. Name the project "First Legal Script".</li>
            <li>Click the <strong>Run</strong> button (triangle icon) in the toolbar.</li>
            <li><strong>Authorization:</strong> Google will ask for permission. This is your script accessing your account.
              <ul className="list-disc pl-4 mt-2 text-sm text-gray-500">
                <li>Click "Review Permissions".</li>
                <li>Choose your account.</li>
                <li>If you see "Google hasn't verified this app" (because you just wrote it), click <strong>Advanced</strong> &rarr; <strong>Go to First Legal Script (unsafe)</strong>. It is safe; you wrote it.</li>
                <li>Click "Allow".</li>
              </ul>
            </li>
          </ol>

          <h2 className="text-2xl font-black uppercase mb-4">Step 4: See The Magic</h2>
          <p className="mb-4">
            At the bottom of the screen, you should see "Execution started" and then "Execution completed".
          </p>
          <p className="mb-4">
            Go to your <a href="https://docs.google.com" target="_blank" className="underline">Google Docs dashboard</a> or Google Drive. Look at the "Recent" files.
          </p>
          <div className="border-l-4 border-brand-teal pl-4 py-2 italic bg-brand-teal/5">
            You should see a new document named "Hello Legal World - Generated by Script". Open it. Read the text.
          </div>

          <h2 className="text-2xl font-black uppercase mt-12 mb-4">Why This Matters</h2>
          <p className="mb-4">
            You didn't just type a document. You created a process that types a document.
          </p>
          <p className="mb-8">
            <strong>Imagine the possibilities:</strong> Instead of hardcoding "Hello World", what if we connected this to a Google Form response? What if we replaced the text with a full contract template? That is exactly what we will do in future tutorials.
          </p>

          <div className="bg-brand-amber border-2 border-black p-6 text-center shadow-brutal">
            <h3 className="font-black uppercase text-xl mb-2">Ready for the Next Level?</h3>
            <p className="font-mono text-sm mb-4">Learn how to connect Gmail to Google Sheets automatically.</p>
            <Link to="/tech/email-to-sheets" className="inline-block px-6 py-2 bg-black text-white font-bold uppercase hover:bg-white hover:text-black transition-colors border-2 border-black">
              Next Tutorial →
            </Link>
          </div>

        </article>
      </div>
    </div>
  );
};